serverConfig:
  host: "0.0.0.0"
  port: 8080
rateLimitConfig:
  rateLimit: 30
  refillSpeed: "PT1M"
webSocketConfig:
  pingPeriod: "PT3S"
  timeout: "PT60S"
encryptionToken: "AIkjDRWCktbcdFJoFzmeoYyfcxtYoMvNcfDmyLpPApqkNdZgzAyMxFMzKsxFKvmQ"
fileConfig:
  profilePictureMaxSize: 200
  gameLogsPath: "logs/game"
currentLogPriority: !<com.example.features.LogPriority.Debug> {}
gameConfig:
  timeForMove: 300000000
  ratingDifference: 200
  bucketSize: 100
  delayBeforeRecheckingBucket: 3000
  minTimeBeforePairingWithBot: 20000
  maxTimeBeforePairingWithBot: 30000
isInKuber: false
