[versions]
kotlin = "2.1.0"
ktor = "3.0.0"
logback_version = "1.4.14"
kotlin_serialization = "1.7.3"
bcrypt = "0.10.2"
kaml = "0.65.0"
exposed_version = "0.56.0"
postgresql = "42.7.4"
nine_mens_morris_shared = "d8439fe65f"
lib = "1.0.2"
otlp = "1.44.1"
otlp_ktor = "2.10.0-alpha"
junit = "5.10.2"
test_container = "1.20.3"
dokka = "1.9.20"
kafka = "2.1.1"

[libraries]
ktor-server-ohhttp = { group = "io.ktor", name = "ktor-server-cors", version.ref = "ktor" }
ktor-server-core-jvm = { group = "io.ktor", name = "ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-content-negotiation-jvm = { group = "io.ktor", name = "ktor-server-content-negotiation-jvm", version.ref = "ktor" }
ktor-serialization-kotlinx-json-jvm = { group = "io.ktor", name = "ktor-serialization-kotlinx-json-jvm", version.ref = "ktor" }
ktor-server-netty-jvm = { group = "io.ktor", name = "ktor-server-netty-jvm", version.ref = "ktor" }
ktor-server-websockets = { group = "io.ktor", name = "ktor-server-websockets", version.ref = "ktor" }
ktor-server-auth-jwt = { group = "io.ktor", name = "ktor-server-auth-jwt", version.ref = "ktor" }
ktor-server-rate-limit = { group = "io.ktor", name = "ktor-server-rate-limit", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-server-cors = { group = "io.ktor", name = "ktor-server-cors", version.ref = "ktor" }
ktor-server-test = { group = "io.ktor", name = "ktor-server-test-host", version.ref = "ktor" }
ktor-server-kafka = { group = "io.github.flaxoos", name = "ktor-server-kafka", version.ref = "kafka" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback_version" }
bcrypt = { group = "at.favre.lib", name = "bcrypt", version.ref = "bcrypt" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin_serialization" }
kaml = { group = "com.charleskorn.kaml", name = "kaml", version.ref = "kaml" }
exposed-core = { group = "org.jetbrains.exposed", name = "exposed-core", version.ref = "exposed_version" }
exposed-jdbc = { group = "org.jetbrains.exposed", name = "exposed-jdbc", version.ref = "exposed_version" }
exposed-kotlin-datetime = { group = "org.jetbrains.exposed", name = "exposed-kotlin-datetime", version.ref = "exposed_version" }
exposed-json = { group = "org.jetbrains.exposed", name = "exposed-json", version.ref = "exposed_version" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
nine-men-s-morris-shared = { group = "com.github.kroune", name = "9-men-s-morris-shared", version.ref = "nine_mens_morris_shared" }
nine-men-s-morris-lib = { group = "io.github.kroune", name = "nineMensMorris-jvm", version.ref = "lib" }
opentelemetry-exporter-otlp = { group = "io.opentelemetry", name = "opentelemetry-exporter-otlp", version.ref = "otlp" }
opentelemetry-sdk = { group = "io.opentelemetry", name = "opentelemetry-sdk", version.ref = "otlp" }
opentelemetry-ktor = { group = "io.opentelemetry.instrumentation", name = "opentelemetry-ktor-3.0", version.ref = "otlp_ktor" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
test-container-postgresql = { group = "org.testcontainers", name = "postgresql", version.ref = "test_container" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }