name: Jar file builder

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Set up JDK 20
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: 20
    - name: Cache Gradlew packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - name: Build jar
      run: ./gradlew build
    - name: Upload jar file
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.date_today }} - ${{ env.repository_name }} - Jar
        path: build/libs/MensMorris-backend-all.jar
