name: Jar file builder

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Set up JDK 20
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: 20
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4    
    - name: Build jar
      run: gradle build
    - name: Upload jar file
      uses: actions/upload-artifact@v4
      with:
        name: $(date +'%Y-%m-%d') - ${{ github.event.repository.name }} - Jar
        path: build/libs/MensMorris-backend-all.jar
