name: Update Kubernetes Deployment

on:
  workflow_run:
    workflows: ["Builds docker image and pushes it"]
    branches: [master]
    types:
      - completed
  workflow_dispatch:

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Generate Docker tag
        id: tag
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')
            COMMIT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)
          else
            BRANCH_NAME=$(echo ${{ github.event.workflow_run.head_branch }} | sed 's/\//-/g')
            COMMIT_SHA=$(echo ${{ github.event.workflow_run.head_sha }} | cut -c1-7)
          fi
          echo "image_tag=${BRANCH_NAME}-${COMMIT_SHA}" >> $GITHUB_OUTPUT

      - name: Checkout deployment repository
        uses: actions/checkout@v4
        with:
          repository: kroune/nmm-deployment
          token: ${{ secrets.PAT_TOKEN }}
          path: deployment-repo

      - name: Update deployment.yaml
        run: |
          cd deployment-repo/game-server
          sed -i "s|image: kroune/nine-mens-morris-server:.*|image: kroune/nine-mens-morris-server:${{ steps.tag.outputs.image_tag }}|g" deployment.yaml

      - name: Commit and push changes
        run: |
          cd deployment-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add game-server/deployment.yaml
          git commit -m "Update image to ${{ steps.tag.outputs.image_tag }}"
          git push
